# fly.toml file generated for fleettracker on 2022-08-27T13:51:28+01:00

app = "fleettracker"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  ALLY_CODES_URL = "http://rotbot.eu/sniper/ac-1007299187345477712-fleet.json"
  ARENA_TYPE = "FLEET"
  DISCORD_WEB_HOOK = "https://discord.com/api/webhooks/1009116991279345674/IaDPRo0iI0BIVXBNCsQN10gQKDUPKmWibZL70vElgYEZZa9SaRZzGaw4K_qQ8SiMoeMn"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  processes = ["app"]
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
